In [1]:
#Array

In [2]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [5]:
zeros_arr=np.zeros((2,3))
ones_arr=np.ones((2,3))
#zeros_arr
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
zeros_arr=np.zeros((2,3))
ones_arr=np.ones((2,3))
zeros_arr
#ones_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arange_arr=np.arange(0, 10, 2)
arange_arr

array([0, 2, 4, 6, 8])

In [14]:


linspace_arr=np.linspace(0, 1, 5)# 5 here means dividing in 5 equal parts
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
random_arr=np.random.rand(2,3)#0to 1 range output
random_arr

array([[0.40712914, 0.42776368, 0.13981166],
       [0.95362456, 0.00582606, 0.01870675]])

In [38]:

random_arr=np.random.randint(low=4,high=5,size=(2,3))
random_arr

array([[4, 4, 4],
       [4, 4, 4]])

In [37]:
#Array indexing and slicing

In [40]:
arr=np.array([1,2,3,4,5])
print(arr[2])
arr[1]

3


2

In [46]:
arr1=np.random.rand(3,3)*9+1
print(arr1)

[[6.78732616 7.90165009 6.72988324]
 [5.64955071 3.23900293 1.90309595]
 [9.57665831 8.02691585 2.69434779]]


In [51]:
arrr=np.array([1,2,3,4,5,6])
print(arrr[2])
arrr[2]=10
arrr

3


array([ 1,  2, 10,  4,  5,  6])

In [61]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8])
newarr= arr.reshape(3,3)
print(newarr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
