In [3]:
if __name__ == '__main__':
    n = int(input())

    def print_sequence(n):
        if 1 <= n <= 150:
            result=0
            for i in range(1, n + 1):
                result = result * 10 + i
            print(result)
    
    print_sequence(n)

10
1234567900


In [5]:
if __name__ == '__main__':
    n = int(input())

    def print_sequence(n):
        if 1 <= n <= 150:
            num_digits = len(str(n))
            result = 0
            for i in range(1, n + 1):
                result = result * 10 + i
            print(result)

    print_sequence(n)


10
1234567900


In [2]:
import numpy

change_array = numpy.array([9,8,7,6,5,4,3,2,1])
change_array.shape = (3,3)
print (change_array)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [1]:
if __name__ == '__main__':
    n = int(input())

    def sequence(n):
        if 1 <= n <= 150:
            result = []
            for i in range(1, n + 1):
                result.extend([int(digit) for digit in str(i)])
            print(*result, sep='')

    sequence(n)

10
12345678910
